import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Main } from "../components/Main";
import { Header } from "../components/Header";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count, setCount] = useState(1);
  const [text, setText] = useState("");
  const [isShow, setIsShow] = useState(true);

  const handleClick = useCallback(
    (e) => {
      console.log(count);

      if (count < 10) {
        setCount((count) => count + 1);
      }
    },
    [count]
  );

  const handleChange = useCallback((e) => {
    if (e.target.value.length > 5) {
      alert("5文字以内にして下さい");
      return;
    }
    setText(e.target.value.trim());
  }, []);

  const handleDiplay = useCallback(() => {
    setIsShow((isShow) => !isShow);
  }, []);

  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";
    return () => {
      document.body.style.backgroundColor = "";
    };
  }, [count]);


  
  console.log(text);
  
  return (
    <>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* 三項演算子 */}
      {isShow ? <h1>{count}</h1> : null}
      <button onClick={handleClick}>ボタン</button>
      <button
        onClick={handleDiplay}
        // onClick={() => {
        //   setIsShow(
        //     (isShow) => !isShow
        //     // if(isShow === true){
        //     //   return false;
        //     // }else{
        //     //   return true;
        //     // }

        //     // if (isShow) {
        //     //   return false;
        //     // } else {
        //     //   return true;
        //     // }

        //     // if (isShow) {
        //     //   return false;
        //     // }
        //     // return true;

        //     // return isShow ? false : true;

        //     // return !isShow;
        //   );
        // }
      >
        {isShow ? "非表示" : "表示"}
      </button>
      <input
        type="text"
        value={text}
        // onChange={(e) => {
        //   if (text.length >= 5) {
        //     return;
        //   }
        //   setText(e.target.value);
        // }}
        onChange={handleChange}
      />
      <Main page="index" />
    </>
  );
}
