import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Main } from "../components/Main";
import { Header } from "../components/Header";
import { useCallback, useEffect } from "react";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const foo = 1;
  // useCallbackを使用してコンポーネント内部にメゾットを記述するとコンポーネントがレンダリングされたとき、一緒に再レンダリングされないためパフォーマンスがよくなる
  const handleClick = useCallback((e) => {
    console.log(e.target.href);
    // preventDefault メソッドを使用することで、イベントが発生したときにイベントに対してブラウザで設定されているデフォルトの動作をキャンセルさせることができます。
    e.preventDefault();
    alert(foo);
  }, []);
  //Homeコンポーネントがマウントされるとき処理される
  useEffect(() => {
    // マウント時の処理
    document.body.style.backgroundColor = "lightblue";
    console.log("マウント時");
    // アンマウント時の処理
    return () => {
      document.body.style.backgroundColor = "";
      console.log("アンマウント時");
    };
  }, []);

  return (
    <>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Link href="/about" onClick={handleClick}>
        ボタン
      </Link>
      <Main page="index" />
    </>
  );
}
